Serverassignment
thottel64/pivotassignments pull request #2
Opened 2022-10-31 17:36 UTC by thottel64

Here is my first attempt at the Server Assignment. I struggled a bit with Delete and Put  requests since we never covered them in class, but I tried my best with some googling.

2022-11-02 01:11 UTC, jboursiquot requested changes
Good start. Still needs work. In addition to inline comments, fix the following:

1. You're `.gitignore` file needs to be at the root of your repo, not inside of `.idea`
2. Recall Monday's class discussion and the reason why you do not commit your `.idea` folder.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +	fmt.Println(o)
No need to print out here. You can use the `log` package if you need to emit something for troubleshooting purposes.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +	fmt.Fprintf(w, "ID = %d\n", ID)
Caution: You're using `%d` for digits but are passing in `ID` which is a string.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +	fmt.Fprintf(w, "Price = %d\n", Price)
Caution: You're using %d for digits but are passing in ID which is a string.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +		log.Fatalln(err)
Prefer a simple `strconv.Atoi` here over the use of `fmt.Sscan`.
Do not `Fatalln` out of a handler. You'll be crashing your entire server over an invalid request parameter. Use the response writer to send back an error/status to the client.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +			_, err = w.Write([]byte(response))
This `err` is never checked.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +func DeleteHandler(w http.ResponseWriter, r *http.Request) {
You have a logic error in your `DeleteHandler`. I've submitted the same ID for deletion multiple times and the product is never actually removed.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +		if products.ID == intid {
You need to actually remove the product from the `products` slice, not blank it out.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +func PutHandler(w http.ResponseWriter, r *http.Request) {
This does not update any product. I assume you'll add this next.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +func PostHandler(w http.ResponseWriter, r *http.Request) {
This does not add a product yet. I assume you'll add this next.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +			_, err = w.Write(response)
This `err` is never checked.

2022-11-02 01:11 UTC, jboursiquot commented on main.go
> +			_, err = w.Write([]byte(response))
This `err` is never checked.

2022-11-08 21:49 UTC, thottel64 commented
Made a mistake. Code is not ready for review.

2022-11-08 22:15 UTC, thottel64 commented
Code should now be ready for review

2022-11-09 02:04 UTC, jboursiquot requested changes

2022-11-09 02:04 UTC, jboursiquot commented on go.mod
> +module github.com/thottel64/pivotassignments/productserver
Your module is `github.com/thottel64/pivotassignments`. Remove the `productserver` portion.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +		log.Fatalln(err)
Do not crash your server with `log.Fatalln`. Return an error back to the client instead.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +			}
Not necessary. You're already sending the appropriate response in the header.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +		if intid > len(product) {
You can do this check outside of the loop. No need to ask the same question multiple times with each loop iteration.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +			_, err = w.Write(response)
You capture `err` but you don't check it.
You can omit capturing the error here.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +
defer the body's close

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +	json.NewEncoder(w).Encode(newProduct)
No need to send the new product back after creating it.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +		if intid > len(product) {
No need to repeat this check with every loop iteration.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +var product []Product
`product` is a slice of products. Use a plural variable name.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +		if intid > len(product) {
No need for this check in every loop iteration.

2022-11-09 02:04 UTC, jboursiquot commented on productserver/main.go
> +			_, err = w.Write([]byte(response))
No need for this response. Communicate with the right response header status code.

2022-11-10 19:37 UTC, jboursiquot commented on productserver/main.go
> +var product []Product
This is still unaddressed.

2022-11-10 19:38 UTC, jboursiquot requested changes
You have an unaddressed change request.

2022-11-10 20:17 UTC, thottel64 commented on productserver/main.go
> +var product []Product
Sorry about that! I've renamed the variable to make the code easier to read.

2022-11-12 03:20 UTC, jboursiquot approved these changes

2022-11-30 01:28 UTC, merged